// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    description: "Salário",
    amount: "1300.52",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Freela",
    amount: "150.13",
    type: "entrada",
    frequency: "eventual",
    date: "2020-01-17",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Salário",
    amount: "2500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Freela",
    amount: "150.13",
    type: "entrada",
    frequency: "eventual",
    date: "2020-01-17",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2020-03-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-02-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-03-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-03-10",
  },
  {
    description: "Salário",
    amount: "2500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-01-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-02-10",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2020-03-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "202-01-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-02-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-03-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-03-10",
  },
  {
    description: "Salário",
    amount: "2500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-01-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-01-10",
  },
];
